In [2]:
#Importing Libraries 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns 
from tensorflow import keras

In [3]:
data = [['0', 'Y', 'N'], ['1', 'Y', 'Y'], ['2', 'N', 'Y'], ['3', 'Y', 'Y'], ['4', 'N', 'N']]
products = pd.DataFrame(data, columns=['product_id', 'low_fats', 'recyclable']).astype({'product_id':'int64', 'low_fats':'category', 'recyclable':'category'})

In [4]:
products

   product_id low_fats recyclable
0           0        Y          N
1           1        Y          Y
2           2        N          Y
3           3        Y          Y
4           4        N          N

In [6]:
result = products[(products['low_fats']=='Y')&(products['recyclable']=='Y')]

In [7]:
result

   product_id low_fats recyclable
1           1        Y          Y
3           3        Y          Y

In [10]:
result['product_id']

1    1
3    3
Name: product_id, dtype: int64